<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>TC_Cura_Login_TestSuite</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>3</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <rerunImmediately>true</rerunImmediately>
   <testSuiteGuid>e726dc6d-2211-4a84-98c9-8583f752d4bf</testSuiteGuid>
   <testCaseLink>
      <guid>62be3f96-641a-4948-bcee-3d9da16d4140</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Recording Modes/TC_Login_Module/TC_CURA_Login_01</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>da4f7ff6-b8aa-4bb5-b927-14d94db93c50</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>dee0e597-0785-4426-91b2-a17d42babc1d</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>af8c22c0-8021-452c-b97f-4232cbf87bd6</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Recording Modes/TC_Login_Module/TC_CURA_Login_02</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
   </testCaseLink>
   <testCaseLink>
      <guid>1eea2c70-ba6f-4fec-94ae-0cd793a93075</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Recording Modes/TC_Login_Module/TC_CURA_Login_03</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>e7e7432e-10e3-45f0-8c3f-bd3a24c98fcd</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>677992d5-e4a5-48fa-a889-c97a759cf555</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>61bde7ed-b1a9-47a5-aac4-b27dbcabfeb4</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
