<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>p_Seoul CURA Healthcare Center</name>
   <tag></tag>
   <elementGuidId>1c4ac5e6-d661-4126-a1b8-9e31e094ef00</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#facility</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//p[@id='facility']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>p</value>
      <webElementGuid>e199a90f-f14f-4f56-8aa9-4ed538eea50c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>facility</value>
      <webElementGuid>fbf14706-2a49-426f-bddf-2898314880c1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Seoul CURA Healthcare Center</value>
      <webElementGuid>94ee9bac-cf4c-4362-9393-43598078e138</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;facility&quot;)</value>
      <webElementGuid>884bb45c-f581-4ed2-a3b6-01471ea60d68</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//p[@id='facility']</value>
      <webElementGuid>48b8f02c-fc1a-4a82-bf63-26de19237e54</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//section[@id='history']/div/div[2]/div/div/div[2]/div[2]/p</value>
      <webElementGuid>b44f8f92-7b75-47f5-ba7f-5fb7b9fbeabb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//p</value>
      <webElementGuid>ec432503-8014-4a04-a322-d85c7c0be3d1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//p[@id = 'facility' and (text() = 'Seoul CURA Healthcare Center' or . = 'Seoul CURA Healthcare Center')]</value>
      <webElementGuid>ac798c3e-db50-41ad-91c7-b9359e97efd8</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
